config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new,:create,:show]
  resources :rewards, only: [:index, :show]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'

  resources :rewards_users, only: [:new, :create]

  namespace :admin do
    resources :rewards
    resources :users
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :rewards_users, dependent: :destroy
  has_many :users, through: :rewards_users
end

app/models/rewards_user.rb
class RewardsUser < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'
require 'pry'


class User < ActiveRecord::Base
  has_many :rewards_users, dependent: :destroy
  has_many :rewards, through: :rewards_users
  
  validates :username, presence: true,
                     uniqueness: true
  has_secure_password

  enum role: ["default", "admin"]

  def buy_reward?(reward_id)
    reward_cost = Reward.find(reward_id.to_i).cost
    if points >= reward_cost
      subtract_points(reward_cost)
    end
  end

  def subtract_points(reward_cost)
    update_attributes(points:(points - reward_cost))
  end


end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end



end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  before_filter :current_user

  def new
    @reward= Reward.new
  end

  def create
    @reward= Reward.new(reward_params)
    if @reward.save
      flash[:notice]= "Reward Created"
      redirect_to rewards_path
    else
      flash[:error]= "Those are not valid inputs"
      render :new
    end
  end

  def destroy
     Reward.find(params[:id]).destroy
     redirect_to rewards_path
  end



private

  def reward_params
    params.require(:reward).permit(:item,:cost)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :current_user

  def new
    @user= User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      flash[:error]= "Those are not valid inputs"
      render :new
    end
  end

  def index
    @users= User.all
  end

  def destroy
    @user=User.find(params[:id]).destroy
    redirect_to admin_users_path
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to admin_users_path
  end



  private

    def user_params
      params.require(:user).permit(:username,:points)
    end

end

app/controllers/application_controller.rb
require 'bcrypt'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end


end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_filter :current_user

  def index
    @rewards= Reward.all
  end

end

app/controllers/rewards_users_controller.rb
require 'pry'

class RewardsUsersController < ApplicationController

  def create
    if current_user.buy_reward?(params[:reward_id])
      rewards_user = RewardsUser.new(user_id: current_user.id, reward_id: params[:reward_id])
      rewards_user.save
    else
      flash.now[:notice] = "Not enough points to complete this transaction"
    end
    redirect_to rewards_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :layout => false
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "Wrong Username or Password"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :is_admin?


  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new
    render :layout => false
  end

  def create
    @user= User.new(user_params)
    if @user.save
      flash[:notice]= "Success"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error]= "Those are not valid inputs"
      render :new
    end
  end



private

  def user_params
    params.require(:user).permit(:username,:password,:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rewards/new.html.erb
<%= flash.now[:error] %>
<%= flash[:notice] %>

<h1> Create a Reward </h1>

<%= form_for [:admin, @reward] do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>
  <br></br>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <br></br>
  <%= f.submit "Create Reward" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1> Edit User </h1>

<%= form_for [:admin, @user] do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br></br>
  <%= f.label :points %>
  <%= f.text_field :points %>
  <br></br>
  <%= f.submit "Edit User" %>
<% end %>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
<h2><%= user.username%></h2>
<p> ID:<%= user.id%></p>
<p> Points:<%= user.points%></p>
<p> Created On:<%= user.created_at %></p>
<%= link_to "Delete", admin_user_path(:id => user.id), method: :delete%>
<br></br>
<%= link_to "Edit or Give points", edit_admin_user_path(:id => user.id)%>
<br></br>
<%end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">PointsBox</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
        <a href="/rewards">Rewards</a>
      </li>
      <li>
        <%if current_user.nil? %>
        <%=link_to "Create An Account", new_user_path %>
        <%else %>
        <a href="/users/<%=(@user.id)%>"><%=@user.username%></a>
        <%end %>
      </li>
      <li>
      <% if current_user.nil? %>
      <%= link_to "Login", login_path %>
      <% else %>
      <%= link_to "Logout", logout_path, method: :delete %>
      <% end %>
    </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
<%= yield %>
</body>
<div>
  <% if current_user.nil? %>
    <%= link_to "Login", login_path %>
  <% else %>
  <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>
</div>
</html>

app/views/rewards/index.html.erb
<% @rewards.each do |reward| %>
    <h3>Reward: <%= reward.item %></h3>
    <h3>Id:<%= reward.id %>
    <h3>Cost: <%= reward.cost %> points</h3>
     <br></br>
    <%= link_to "Delete", admin_reward_path(:id => reward.id), method: :delete if current_user.admin?%>
    <br></br>
    <%= link_to "Redeem", rewards_users_path(reward_id: reward.id), method: :post %>
  <%end %>
<%=link_to "New Reward", new_admin_reward_path%>

app/views/users/new.html.erb
<%= flash.now[:error] %>
<%= flash[:notice] %>

<h1> Create an Account </h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br></br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br></br>
  <%= f.text_field :role %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h2>Hello, <%=@user.username%>.</h2>

<h1>Points: <%= @user.points %></h1>
<h1>Rewards:<% @user.rewards.each do |reward| %></h1>
  <p><%=reward.item %></p>
  <%end %>


<%= link_to "See All Users", admin_users_path if current_user.admin? %>